modified troubleshooting script

diff --git a/.github/workflows/app_troubleshoot.yml b/.github/workflows/app_troubleshoot.yml
--- a/.github/workflows/app_troubleshoot.yml
+++ b/.github/workflows/app_troubleshoot.yml
@@ -38,6 +38,11 @@ on:
         required: false
         default: true
         type: boolean
+      create_backup:
+        description: 'Create backup'
+        required: false
+        default: true 
+        type: boolean
 
 jobs:
   list-wp-plugins:
@@ -71,6 +76,19 @@ jobs:
   configure-app:
     if: github.event.inputs.configure_app == 'true'
     uses: ./.github/workflows/app_configure.yml
+  create-backup:
+    if: github.event.inputs.create_backup == 'true'
+    runs-on: self-hosted
+    steps:
+      - name: run backup script
+        run: |
+          if [ -f "./scripts/wordpress-backup.sh" ]; then
+            chmod +x ./scripts/wordpress-backup.sh
+            ./scripts/wordpress-backup.sh
+          else
+            echo "Backup script not found!"
+            exit 1
+          fi
   check-containers:
     if: github.event.inputs.check_containers == 'true'
     runs-on: self-hosted
